---
# tasks file for mysql
  - name: install python3 MySQL-python
    yum:
      name: python3, MySQL-python
      state: present

  - name: Install MySQL
    yum:
      name: mariadb-server
      state: present

  - name: Start and Enable MySQL
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: for MySQL create database
    mysql_db:
      login_unix_socket: /var/lib/mysql/mysql.sock
      name: db
      state: present

  - name: for MySQL create user
    mysql_user:
      login_unix_socket: /var/lib/mysql/mysql.sock
      name: user
      password: 12345
      priv: '*.*:ALL'
      state: present

