---
# tasks file for nginx

  - name: install nginx
    become: yes
    yum:
      name: nginx
      state: present

  - name: Start nginx
    become: yes
    service:
      name: nginx
      state: started
      enabled: true

  - name: creates directory /web
    become: yes
    file:
      path: /web
      state: directory
      owner: nginx
      group: nginx
      mode: 0775

  - name: place there files for some test site
    become: yes
    copy:
      src: index.html
      dest: /web/index.html
      owner: nginx
      group: nginx
      mode: 0644

  - name: change nginx config
    become: yes
    template:
      src: nginx.j2.conf
      dest: /etc/nginx/nginx.conf
      owner: nginx
      group: nginx
      mode: 0644
    vars:
      nginx_root_dir: "/web"
    notify:
      - restart nginx
                              
#ansible-galaxy collection install ansible.posix
  - name: open port 80
    become: yes
    firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: enabled
    notify:
      - Restart firewalld

  - name: disable selinux
    become: yes
    selinux:
      state: disabled

